version: "3.8"
services:
  postgres:
    image: postgres:16
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: "postgres -c max_connections=200 -c wal_level=logical"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    command: "bin/dev"
    tty: true
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/pictoplan
    depends_on:
      postgres:
        condition: service_healthy
